#include "Exception.hpp"

int Exception::getNumber()
{
    return number;
}